[package]
name = "upng"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libc = "0.2.174"

[dev-dependencies]
glu-sys = "0.1.4"
libc = "0.2.161"
libc-stdhandle = "0.1.0"
sdl2-sys = "0.37.0"
sdl = "0.3.6"

[build-dependencies]
cbindgen = "0.29.0"
